"""
E2E tests that generate complete step-by-step guide for ForgeERP.

To generate documentation, run:
    pytest tests/e2e/test_guia_completo.py --generate-docs -v

Or use Makefile:
    make docs-e2e
"""

import pytest
from pathlib import Path
from datetime import datetime
from playwright.sync_api import Page
import time

from tests.e2e.utils import wait_for_react, wait_for_navigation_complete


@pytest.fixture
def docs_output_dir(request):
    """Output directory for generated documentation"""
    output_dir = Path("docs/operacional/screenshots")
    output_dir.mkdir(parents=True, exist_ok=True)
    return output_dir


@pytest.fixture
def should_generate_docs(request):
    """Check if documentation should be generated"""
    return request.config.getoption("--generate-docs")


class CompleteGuide:
    """Helper class to generate complete step-by-step guide"""
    
    def __init__(self, page: Page, output_dir: Path):
        self.page = page
        self.output_dir = output_dir
        self.steps = []
        self.step_number = 1
    
    def add_step(self, title: str, instructions: list, screenshot_name: str):
        """Add a documentation step"""
        screenshot_path = self.output_dir / f"{screenshot_name}.png"
        self.page.screenshot(path=str(screenshot_path), full_page=True)
        
        step = {
            "step": self.step_number,
            "title": title,
            "instructions": instructions,
            "screenshot": f"operacional/screenshots/{screenshot_name}.png",
            "screenshot_name": screenshot_name
        }
        
        self.steps.append(step)
        self.step_number += 1
        return step
    
    def generate_markdown(self, filename: str = "STEP_BY_STEP_GUIDE.md"):
        """Generate step-by-step markdown documentation"""
        md_path = self.output_dir.parent / filename
        md_path.parent.mkdir(parents=True, exist_ok=True)
        
        with open(md_path, "w", encoding="utf-8") as f:
            f.write(f"# 📖 Step-by-Step Guide - ForgeERP\n\n")
            f.write(f"This guide was automatically generated by E2E tests.\n\n")
            f.write(f"**Generated on:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n")
            f.write("---\n\n")
            
            f.write("## 📋 Table of Contents\n\n")
            for step in self.steps:
                anchor = step['title'].lower().replace(' ', '-').replace(':', '').replace("'", "")
                f.write(f"{step['step']}. [{step['title']}](#step-{step['step']}-{anchor})\n")
            f.write("\n---\n\n")
            
            for step in self.steps:
                anchor = step['title'].lower().replace(' ', '-').replace(':', '').replace("'", "")
                f.write(f"## Step {step['step']}: {step['title']}\n\n")
                f.write(f"![{step['screenshot_name']}]({step['screenshot']})\n\n")
                
                f.write("### What to do:\n\n")
                for i, instruction in enumerate(step['instructions'], 1):
                    f.write(f"{i}. {instruction}\n")
                
                f.write("\n---\n\n")
        
        print(f"✅ Guide generated at: {md_path}")


def test_complete_guide(
    page: Page, 
    docs_output_dir: Path, 
    should_generate_docs: bool, 
    frontend_url: str, 
    api_url: str
):
    """Complete test that generates step-by-step guide for all features"""
    if not should_generate_docs:
        pytest.skip("Run with --generate-docs to generate documentation")
    
    guide = CompleteGuide(page, docs_output_dir)
    
    # ============================================
    # STEP 1: Access the application
    # ============================================
    page.goto(frontend_url, wait_until="networkidle", timeout=30000)
    wait_for_react(page)
    time.sleep(2)  # Wait for complete rendering
    
    guide.add_step(
        "Access the application",
        [
            f"Open your browser and navigate to: {frontend_url}",
            "The login page will be displayed automatically",
            "You will see the login form with username and password fields"
        ],
        "01_access_application"
    )
    
    # ============================================
    # STEP 2: Login
    # ============================================
    # Fill username
    username_selectors = [
        'input[id="username"]',
        'input[type="text"]',
        'input[placeholder*="admin"]',
    ]
    for selector in username_selectors:
        try:
            input_field = page.locator(selector).first
            if input_field.count() > 0:
                input_field.fill("admin")
                break
        except:
            continue
    
    time.sleep(1)
    guide.add_step(
        "Fill username field",
        [
            "In the 'Username' field, type: **admin**",
            "This is the default system username",
            "The field accepts text only"
        ],
        "02_fill_username"
    )
    
    # Fill password
    try:
        password_input = page.locator('input[type="password"]').first
        if password_input.count() > 0:
            password_input.fill("admin")
    except Exception as e:
        print(f"⚠️  Could not fill password: {e}")
    
    time.sleep(1)
    guide.add_step(
        "Fill password field",
        [
            "In the 'Password' field, type: **admin**",
            "This is the default system password",
            "The password is hidden for security (appears as ••••••••)"
        ],
        "03_fill_password"
    )
    
    # Click login
    submit_selectors = [
        'button[type="submit"]',
        'button:has-text("Login")',
        'button:has-text("Entrar")',
    ]
    for selector in submit_selectors:
        try:
            button = page.locator(selector).first
            if button.count() > 0:
                button.click()
                time.sleep(3)
                wait_for_navigation_complete(page)
                break
        except:
            continue
    
    guide.add_step(
        "Click 'Login'",
        [
            "Click the **'Login'** button",
            "The system will validate your credentials",
            "If correct, you will be redirected to the dashboard"
        ],
        "04_login_success"
    )
    
    # ============================================
    # STEP 5: Dashboard
    # ============================================
    time.sleep(2)  # Wait for dashboard to load
    wait_for_react(page)
    
    guide.add_step(
        "View Dashboard",
        [
            "After logging in, you will see the **Dashboard**",
            "At the top, there is a navigation menu with: Dashboard, Clients, Configurations",
            "In the center, you will see statistics and a list of recent clients"
        ],
        "05_dashboard"
    )
    
    # ============================================
    # STEP 6: Navigate to Clients
    # ============================================
    try:
        # Try to find Clients link
        client_links = [
            'a[href="/clients"]',
            'text=Clients',
            'button:has-text("Clients")',
        ]
        for selector in client_links:
            try:
                element = page.locator(selector).first
                if element.count() > 0:
                    element.click()
                    wait_for_navigation_complete(page)
                    break
            except:
                continue
        
        time.sleep(2)
        wait_for_react(page)
        
        guide.add_step(
            "Navigate to Clients page",
            [
                "Click the **'Clients'** tab in the top menu",
                "You will be redirected to the client management page",
                "Here you can create, edit, and delete clients"
            ],
            "06_clients_page"
        )
    except Exception as e:
        print(f"⚠️  Could not navigate to Clients: {e}")
    
    # ============================================
    # STEP 7: Create new client
    # ============================================
    try:
        # Look for "New Client" button or "+"
        create_buttons = [
            'button:has-text("New Client")',
            'button:has-text("+ New Client")',
            'button:has-text("+")',
        ]
        for selector in create_buttons:
            try:
                button = page.locator(selector).first
                if button.count() > 0:
                    button.click()
                    time.sleep(1)
                    wait_for_react(page)
                    break
            except:
                continue
        
        time.sleep(1)
        
        guide.add_step(
            "Click 'New Client'",
            [
                "Click the **'+ New Client'** button at the top of the page",
                "A form will be displayed to create a new client"
            ],
            "07_create_client_form"
        )
        
        # Fill form
        try:
            # Name
            name_inputs = [
                'input[placeholder*="Name"]',
                'input[type="text"]',
            ]
            for selector in name_inputs:
                try:
                    input_field = page.locator(selector).first
                    if input_field.count() > 0:
                        input_field.fill("Example Client")
                        break
                except:
                    continue
            
            time.sleep(0.5)
            
            # Code
            code_inputs = [
                'input[placeholder*="code"]',
                'input[placeholder*="Code"]',
            ]
            for selector in code_inputs:
                try:
                    input_field = page.locator(selector).first
                    if input_field.count() > 0:
                        input_field.fill("example-client")
                        break
                except:
                    continue
            
            time.sleep(0.5)
            
            guide.add_step(
                "Fill client data",
                [
                    "In the **'Name'** field, type: Example Client",
                    "In the **'Code'** field, type: example-client",
                    "The code must be unique and cannot be changed after creation",
                    "Also fill Email, Domain, and Namespace Prefix (optional)"
                ],
                "08_fill_client_data"
            )
            
            # Click create
            submit_buttons = [
                'button:has-text("Create")',
                'button[type="submit"]',
            ]
            for selector in submit_buttons:
                try:
                    button = page.locator(selector).first
                    if button.count() > 0:
                        button.click()
                        time.sleep(2)
                        wait_for_navigation_complete(page)
                        break
                except:
                    continue
            
            time.sleep(2)
            wait_for_react(page)
            
            guide.add_step(
                "Save client",
                [
                    "Click the **'Create'** button",
                    "The client will be saved to the database",
                    "You will be redirected to the clients list"
                ],
                "09_client_created"
            )
        except Exception as e:
            print(f"⚠️  Could not fill form: {e}")
    except Exception as e:
        print(f"⚠️  Could not create client: {e}")
    
    # ============================================
    # STEP 10: List clients
    # ============================================
    time.sleep(2)
    wait_for_react(page)
    
    guide.add_step(
        "View clients list",
        [
            "On the Clients page, you will see a table with all registered clients",
            "The table shows: Name, Code, Email, Domain, Status, and Actions",
            "You can edit or delete clients by clicking the corresponding buttons"
        ],
        "10_clients_list"
    )
    
    # ============================================
    # STEP 11: Edit client
    # ============================================
    try:
        # Look for "Edit" button
        edit_buttons = [
            'button:has-text("Edit")',
            'a:has-text("Edit")',
        ]
        for selector in edit_buttons:
            try:
                button = page.locator(selector).first
                if button.count() > 0:
                    button.click()
                    time.sleep(2)
                    wait_for_react(page)
                    break
            except:
                continue
        
        time.sleep(1)
        
        guide.add_step(
            "Edit client",
            [
                "Click the **'Edit'** button on the desired client row",
                "The form will be filled with the client data",
                "You can modify the fields (except the code)",
                "Click **'Update'** to save the changes"
            ],
            "11_edit_client"
        )
    except Exception as e:
        print(f"⚠️  Could not edit client: {e}")
    
    # ============================================
    # STEP 12: Navigate to Configurations
    # ============================================
    try:
        config_links = [
            'a[href="/configurations"]',
            'text=Configurations',
            'button:has-text("Configurations")',
        ]
        for selector in config_links:
            try:
                element = page.locator(selector).first
                if element.count() > 0:
                    element.click()
                    wait_for_navigation_complete(page)
                    break
            except:
                continue
        
        time.sleep(2)
        wait_for_react(page)
        
        guide.add_step(
            "Navigate to Configurations",
            [
                "Click the **'Configurations'** tab in the top menu",
                "You will be redirected to the configurations page",
                "Here you can manage global system configurations"
            ],
            "12_configurations_page"
        )
    except Exception as e:
        print(f"⚠️  Could not navigate to Configurations: {e}")
    
    # ============================================
    # STEP 13: Logout
    # ============================================
    try:
        logout_buttons = [
            'button:has-text("Logout")',
            'text=Logout',
        ]
        for selector in logout_buttons:
            try:
                button = page.locator(selector).first
                if button.count() > 0:
                    button.click()
                    time.sleep(2)
                    wait_for_navigation_complete(page)
                    break
            except:
                continue
        
        time.sleep(1)
        wait_for_react(page)
        
        guide.add_step(
            "Logout",
            [
                "Click the **'Logout'** button in the top right corner",
                "You will be logged out and redirected to the login page",
                "To access again, you will need to log in again"
            ],
            "13_logout"
        )
    except Exception as e:
        print(f"⚠️  Could not logout: {e}")
    
    # Generate final documentation
    guide.generate_markdown()
    
    print(f"\n✅ Complete guide generated with {len(guide.steps)} steps!")
